---
fixtures:
  forge_modules:
    stdlib:
      repo: puppetlabs-stdlib
      ref: 6.3.0
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'https://github.com/puppetlabs/provision.git'
