# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/chriskuehl/puppet-pre-commit-hooks.git
  rev: v2.2.0
  hooks:
    - id: epp-validate
    - id: erb-validate
    - id: puppet-lint
      args:
        -   --fail-on-warnings
    - id: puppet-validate
    - id: r10k-validate
    - id: ruby-validate
- repo: https://github.com/jumanjihouse/pre-commit-hooks
  rev: 2.1.6
  hooks:
    # - id: reek
    - id: rubocop
      args: ['-c', '/usr/local/users/jim/dev/puppet/wtfmasterless/.rubocop.yml']
- repo: 'https://github.com/adrienverge/yamllint'
  rev: v1.26.3
  hooks:
    - id: 'yamllint'
- repo: 'https://github.com/gruntwork-io/pre-commit'
  rev: v0.1.17
  hooks:
    - id: 'shellcheck'
      #args: ["--enable require-variable-braces,deprecate-which"]
- repo: https://github.com/psf/black
  rev: 22.3.0 #stable 0
  hooks:
  - id: black
    language_version: python3
