#!/bin/bash
# vim:sta:et:sw=2:ts=2:syntax=sh
#
# Revision History:
# 20180106 - que - initial version
# 20201230 - que - shellcheck corrections
#

SCRIPT=$(basename "$0")
VERSION=1.0.1
VERBOSE=0
DEBUG=0
ERRORS=0

function usage {
  cat << EOM
usage: $SCRIPT [-d] [-h] [-v] [-V]
  where:
    -d specify debug mode
    -h show this message and exit
    -v add verbosity
    -V show version and exit
EOM
  exit 1
}

while getopts ":dhvV" opt
do
  case "$opt" in
    d )
      ((DEBUG+=1))
      ((VERBOSE+=1))
    ;;
    h )
      usage
    ;;
    v ) ((VERBOSE+=1)) ;;
    V )
      echo "$SCRIPT VERSION: $VERSION"
      exit 0
    ;;
    * )
      echo "Unexpected option \"$opt\""
      usage
    ;;
  esac
done
shift $((OPTIND - 1))

GRUBCFG=/etc/grub2-efi.cfg

if [ ! -r "$GRUBCFG" ]
then
  GRUBCFG=/etc/grub2.cfg
fi

if [ -r "$GRUBCFG" ]
then
  awk -F\' '$1=="menuentry " {print i++ " : " $2}' "$GRUBCFG"
  echo
  grub2-editenv list
  echo
  echo "run \"grub2-set-default index ( where index is 0 based of list above )\" to change the default"
  echo
else
  ((ERRORS==1))
  echo "File not (found|readable): $GRUBCFG" >&2
fi

exit "$ERRORS"
