#!/bin/bash
# vim:sta:et:sw=2:ts=2:syntax=sh
# Revision History:
# 20170719 - que - initial version
#

SCRIPT=$(basename "$0")
VERSION='$Revision: 2.0.0 $'
VERBOSE=0
DEBUG=""
ERRORS=0

function usage {
  cat << EOM
usage: $SCRIPT [-d] [-h] [-v] [-V]
  where:
    -d specify debug mode
    -h show this message and exit
    -v add verbosity
    -V show version and exit

    show 20 pids from lsof in revrse order
    I can't for my life remeber why i wanted or needed this
EOM
  exit 1
}

while getopts ":dhvV" opt
do
  case "$opt" in
    d )
      DEBUG=--debug
      ((VERBOSE+=1))
    ;;
    h )
      usage
    ;;
    v ) ((VERBOSE+=1)) ;;
    V )
      echo "$SCRIPT VERSION: $VERSION"
      exit 0
    ;;
    * )
      echo "Unexpected option \"$opt\""
      usage
    ;;
  esac
done
shift $((OPTIND - 1))

TMPFIL=/tmp/fosl.$$

lsof > $TMPFIL
cat $TMPFIL| awk '{ print $2 " " $1; }' | sort -rn | uniq -c | sort -rn | head -20
echo "view all output in: $TMPFIL"
exit $?
