#!/bin/bash
# -*- Mode: Bash; tab-width: 2; indent-tabs-mode: nil -*- vim:sta:et:sw=2:ts=2:syntax=sh
#
# Revision History:
# 20160806 - quiensabe - initial version
#

SCRIPT=$(basename "$0")
VERSION='$Revision: 2123 $'
VERBOSE=0
DEBUG=0
ERRORS=0
RANGE=yesterday
SERVICE=''
DETAIL=10

function usage {
  cat << EOM
usage: $SCRIPT [-d level] [-h] [-r range] [-v] [-V] -s service
  where:
    -d level   - specify detail level (default 10)
    -h         - show this message and exit
    -r range   - (default: yesterday)
    -s service - required parameter
    -v         - add verbosity
    -V         - show version and exit
EOM
  exit 1
}

while getopts ":d:hr:s:vV" opt
do
  case "$opt" in
    d )
      DETAIL="$OPTARG"
    ;;
    h )
      usage
    ;;
    r )
      RANGE="$OPTARG"
    ;;
    s )
      SERVICE="$OPTARG"
    ;;
    v ) ((VERBOSE+=1)) ;;
    V )
      echo "$SCRIPT VERSION: $(echo $VERSION | awk '{ print $2 }')"
      exit 0
    ;;
    * )
      echo "Unexpected option \"$opt\""
      usage
    ;;
  esac
done
shift $((OPTIND - 1))

if [ -z "$SERVICE" ]
then
  SERVICE="$1"
fi

if [ -z "$SERVICE" ]
then
  echo "Missing required parameter: service" >&2
  usage
fi

OUTPUT_FILE=/tmp/lwpeek-${SERVICE}.txt

logwatch --service "$SERVICE" --detail $DETAIL --output stdout --format text --range "$RANGE" > $OUTPUT_FILE
RC=$?

echo "Output saved in: $OUTPUT_FILE"
echo "Displaying now with less command."

less $OUTPUT_FILE

exit $RC
