#!/bin/bash
# -*- Mode: Bash; tab-width: 2; indent-tabs-mode: nil -*- vim:sta:et:sw=2:ts=2:syntax=sh
# Revision History:
# 20180811 - que - initial version
#

SCRIPT=$(basename "$0")
VERSION='$Revision: 1.0.0 $' # will be replaced by svn commit # if using subversion with Revision keywords on
VERBOSE=0
DEBUG=0
ERRORS=0
LAST=1
LFN=''

function usage {
  cat << EOM
usage: $SCRIPT [-a] [-d] [-h] [-l log] [-v] [-V]
  where:
    -a show all
    -d specify debug mode
    -h show this message and exit
    -l specify log file
    -v add verbosity
    -V show version and exit
EOM
  exit 1
}

while getopts ":adhl:vV" opt
do
  case "$opt" in
    a ) LAST=0 ;;
    d )
      ((DEBUG+=1))
      ((VERBOSE+=1))
    ;;
    h )
      usage
    ;;
    l )
      LFN="$OPTARG"
    ;;
    v ) ((VERBOSE+=1)) ;;
    V )
      echo "$SCRIPT VERSION: $(echo $VERSION | awk '{ print $2 }')"
      exit 0
    ;;
    * )
      echo "Unexpected option \"$opt\""
      usage
    ;;
  esac
done
shift $((OPTIND - 1))

if [ -z "$LFN" ]
then
  case "$(facter osfamily)" in
    Debian )
      LFN=/var/log/syslog
    ;;
    * )
      LFN=/var/log/messages
    ;;
  esac
fi

if [ -r "$LFN" ]
then
  SUDO=''
else
  SUDO=sudo
fi

if [ $LAST -ne 0 ]
then
  PID=$($SUDO tac "$LFN" | grep 'puppet-agent' | grep -v 'systemd-tmpfiles' | head -1 | perl -e '$v=<STDIN>; if($v=~/\[(\d+)\]:/) { printf "$1\n"; }')

  $SUDO tac "$LFN" | grep "puppet-agent\[$PID\]:" | tac
else
  $SUDO grep 'puppet-agent' "$LFN"
fi

# ERRORS=$((ERRORS+=1)) # darn ubuntu default dash shell
exit $ERRORS
