#!/bin/bash
# vim:sta:et:sw=2:ts=2:syntax=sh
#
# Revision History:
# 20180811 - que - initial version
# 20210101 - que - shellcheck corrections
#

SCRIPT=$(basename "$0")
VERSION=1.0.1
VERBOSE=0
DEBUG=0
ERRORS=0
LAST=0

function usage {
  cat << EOM
usage: $SCRIPT [-d] [-h] [-l] [-v] [-V]
  where:
    -d specify debug mode
    -h show this message and exit
    -l show last (most recent) run only
    -v add verbosity
    -V show version and exit
EOM
  exit 1
}

while getopts ":dhlvV" opt
do
  case "$opt" in
    d )
      ((DEBUG+=1))
      ((VERBOSE+=1))
    ;;
    h )
      usage
    ;;
    l ) ((LAST+=1)) ;;
    v ) ((VERBOSE+=1)) ;;
    V )
      echo "$SCRIPT VERSION: $VERSION"
      exit 0
    ;;
    * )
      echo "Unexpected option \"$opt\""
      usage
    ;;
  esac
done
shift $((OPTIND - 1))

case "$(facter osfamily)" in
  Debian )
    LFN=/var/log/syslog
  ;;
  * )
    LFN=/var/log/messages
  ;;
esac

if [ -r "$LFN" ]
then
  SUDO=''
else
  SUDO=sudo
fi

if [ -f "$LFN" ]
then
  if [ "$LAST" -ne 0 ]
  then
    PID=$($SUDO tac "$LFN" | grep 'puppet-agent' | head -1 | perl -e '$v=<STDIN>; if($v=~/\[(\d+)\]:/) { printf "$1\n"; }')
    $SUDO tac "$LFN" | grep "puppet-agent\[$PID\]:" | tac
  else
    $SUDO grep 'puppet-agent' "$LFN"
  fi
else
  echo "File not found: $LFN" >&2
  ((ERRORS+=1))
fi

# ERRORS=$((ERRORS+=1)) # darn ubuntu default dash shell
exit "$ERRORS"
