#!/bin/bash
# vim:sta:et:sw=2:ts=2:syntax=sh
#
# Revision History:
# 20180512- que - initial version
# 20210101 - que - shellcheck corrections
#

SCRIPT=$(basename "$0")
VERSION=1.0.0
VERBOSE=0
DEBUG=0
ERRORS=0

function usage {
  cat << EOM
usage: $SCRIPT [-d] [-h] [-v] [-V]
  where:
    -d specify debug mode
    -h show this message and exit
    -v add verbosity
    -V show version and exit
EOM
  exit 1
}

while getopts ":dhvV" opt
do
  case "$opt" in
    d )
      ((DEBUG+=1))
      ((VERBOSE+=1))
    ;;
    h )
      usage
    ;;
    v ) ((VERBOSE+=1)) ;;
    V )
      echo "$SCRIPT VERSION: $VERSION"
      exit 0
    ;;
    * )
      echo "Unexpected option \"$opt\""
      usage
    ;;
  esac
done
shift $((OPTIND - 1))

RCFILE=/opt/nixadmutils/etc/nixadmutils.rc

if [ -r "$RCFILE" ]
then
  # shellcheck source=/dev/null
  . "$RCFILE"
else
  echo "File not (found|readable): $RCFILE" >&2
  exit 1
fi

if [ ! -f "$RKHUNTERLOG" ]
then
  echo "rkhunter.log not found: $RKHUNTERLOG" >&2
  exit 1
fi

if [ "$(whoami)" != "root" ]
then
  PREFIX=sudo
else
  PREFIX=''
fi

$PREFIX /usr/share/rkhunter/scripts/checkWhiteList.sh

exit "$ERRORS"
