#!/bin/bash
# -*- Mode: Bash; tab-width: 2; indent-tabs-mode: nil -*- vim:sta:et:sw=2:ts=2:syntax=sh
#
# Revision History:
# 20180128 - quiensabe - initial version
#

SCRIPT=$(basename "$0")
VERSION='$Revision: 0.1.1 $'
VERBOSE=0
DEBUG=0
ERRORS=0

function usage {
  cat << EOM
usage: $SCRIPT [-d] [-h] [-v] [-V]
  where:
    -d specify debug mode
    -h show this message and exit
    -v add verbosity
    -V show version and exit
EOM
  exit 1
}

while getopts ":dhvV" opt
do
  case "$opt" in
    d )
      ((DEBUG+=1))
      ((VERBOSE+=1))
    ;;
    h )
      usage
    ;;
    v ) ((VERBOSE+=1)) ;;
    V )
      echo "$SCRIPT VERSION: $(echo $VERSION | awk '{ print $2 }')"
      exit 0
    ;;
    * )
      echo "Unexpected option \"$opt\""
      usage
    ;;
  esac
done
shift $((OPTIND - 1))

RCFILE=/opt/nixadmutils/etc/nixadmutils.rc

if [ -r "$RCFILE" ]
then
  . "$RCFILE"
else
  echo "File not (found|readable): $RCFILE" >&2
  exit 1
fi

if [ ! -f "$RKHUNTERLOG" ]
then
  echo "rkhunter.log not found: $RKHUNTERLOG" >&2
  exit 1
fi

if [ "$(whoami)" != "root" ]
then
  PREFIX=sudo
else
  PREFIX=''
fi

$PREFIX grep 'Info: Start date' "$RKHUNTERLOG"
$PREFIX grep -A 1 -e "\[ Warning \]" -e "Warning:" "$RKHUNTERLOG"

exit $ERRORS
