#!/bin/bash
# -*- Mode: Bash; tab-width: 2; indent-tabs-mode: nil -*- vim:sta:et:sw=2:ts=2:syntax=sh
#
# Revision History:
# 20180526 - quiensabe - initial version
#

SCRIPT=$(basename "$0")
VERSION='$Revision: 0.1.1 $'
VERBOSE=0
DEBUG=0
ERRORS=0

function usage {
  cat << EOM
usage: $SCRIPT [-d] [-h] [-v] [-V]
  where:
    -d specify debug mode
    -h show this message and exit
    -v add verbosity
    -V show version and exit
EOM
  exit 1
}

while getopts ":dhvV" opt
do
  case "$opt" in
    d )
      ((DEBUG+=1))
      ((VERBOSE+=1))
    ;;
    h )
      usage
    ;;
    v ) ((VERBOSE+=1)) ;;
    V )
      echo "$SCRIPT VERSION: $(echo $VERSION | awk '{ print $2 }')"
      exit 0
    ;;
    * )
      echo "Unexpected option \"$opt\""
      usage
    ;;
  esac
done
shift $((OPTIND - 1))

if [ "$(whoami)" != "root" ]
then
  PREFIX=sudo
else
  PREFIX=''
fi

FAM=$(facter osfamily)
MDR=$(facter operatingsystemmajrelease)

case "$FAM" in
  Debian )
    $PREFIX apt update
    $PREFIX apt upgrade
    if [ -f /var/run/reboot-required ]; then
      echo 'reboot required'
    fi
  ;;
  RedHat )
    if [ $MDR -gt 7 ]
    then
      $PREFIX dnf --refresh upgrade
    else
      $PREFIX yum update
    fi
    $PREFIX needs-restarting
    RC=$?
    echo "needs-retarting exited with: $RC"
  ;;
  * )
    echo "Unsupported osfamily: $FAM" >&2
    ((ERRORS+=1))
  ;;
esac

exit $ERRORS
